# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-04 16:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quizbot', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='botuser',
            old_name='fb_id',
            new_name='platform_id',
        ),
        migrations.AlterField(
            model_name='answer',
            name='paper',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='quizbot.AttemptedPaper'),
        ),
        migrations.AlterField(
            model_name='option',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='quizbot.Question'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='quizbot.Subject'),
        ),
    ]
